### ISSUE TITLE
Difference in your project compared to ngx-errors

### ISSUE THREAD

**Issue by m0t0r** [Ninja-Squad/ngx-valmes#6]
Hey @cexbrayat,

I am very sorry to bother you, but I just saw your repo in the github timeline and it looks like it's very much the same as https://github.com/UltimateAngular/ngx-errors. (though, it lacks good maintenance) Is there any difference in your project ?

Thanks

**Comment by cexbrayat** [comment]
Hi @m0t0r 👋 

No bother. 

Well first it's working with `FormsModule` and `ReactiveFormsModule` when it looks like `ngx-errors` does not. 

We have a slightly different approach, using `ng-template` to not evaluate the error message if not needed. 

And this just the skeleton to init the repository, but we plan to add a bunch of features to have default messages, that could be configured for the whole application via a service, support i18n, choose a default behavior (display all errors or just one), maybe helpers to write form unit tests more easily... 

I'm not saying `ngx-errors` is not a good idea, we are just trying something slightly different. We'll see how that goes!
